### PR TITLE
integration: docker: Fix diff test by making sure the container runs

### LINKED ISSUE #705: integration: docker: Issue highlighted by agent PR #162
The CI running on https://github.com/clearcontainers/agent/pull/162 has been failing here:

```
00:19:45.998 diff inspect changes in a container 
00:19:45.999   should retrieve the change
00:19:45.999   /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/diff_test.go:47
00:19:45.999 Running command '/usr/bin/docker [docker run --runtime cc-runtime --name ocURGr8CdCYfbKgSWYdGqE9nPWOI4q -d busybox sh]'
00:19:51.708 [docker run --runtime cc-runtime --name ocURGr8CdCYfbKgSWYdGqE9nPWOI4q -d busybox sh]
00:19:51.708 Timeout: 60 seconds
00:19:51.708 Exit Code: 0
00:19:51.708 Stdout: a808280372bfc031ca08b6863f7b1bc32d0d40de5613a2b8dfb71ef249f7c676
00:19:51.708 
00:19:51.708 Stderr: 
00:19:51.708 Running command '/usr/bin/docker [docker exec ocURGr8CdCYfbKgSWYdGqE9nPWOI4q mkdir FirstDirectory]'
00:19:52.089 command failed error 'exit status 126'
00:19:52.090 [docker exec ocURGr8CdCYfbKgSWYdGqE9nPWOI4q mkdir FirstDirectory]
00:19:52.090 Timeout: 60 seconds
00:19:52.090 Exit Code: 126
00:19:52.090 Stdout: oci runtime error: Container not running, impossible to enter
00:19:52.090 
00:19:52.090 Stderr: 
00:19:52.090 Running command '/usr/bin/docker [docker rm -f ocURGr8CdCYfbKgSWYdGqE9nPWOI4q]'
00:19:52.932 [docker rm -f ocURGr8CdCYfbKgSWYdGqE9nPWOI4q]
00:19:52.932 Timeout: 60 seconds
00:19:52.932 Exit Code: 0
00:19:52.933 Stdout: ocURGr8CdCYfbKgSWYdGqE9nPWOI4q
00:19:52.933 
00:19:52.933 Stderr: 
00:19:52.933 Running command '/usr/bin/docker [docker ps -a -f name=ocURGr8CdCYfbKgSWYdGqE9nPWOI4q --format {{.Status}}]'
00:19:52.947 [docker ps -a -f name=ocURGr8CdCYfbKgSWYdGqE9nPWOI4q --format {{.Status}}]
00:19:52.947 Timeout: 60 seconds
00:19:52.947 Exit Code: 0
00:19:52.947 Stdout: 
00:19:52.947 Stderr: 
00:19:52.963 
00:19:52.963 • Failure in Spec Setup (BeforeEach) [6.967 seconds]
00:19:52.964 diff
00:19:52.964 /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/diff_test.go:49
00:19:52.964   inspect changes in a container [BeforeEach]
00:19:52.965   /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/diff_test.go:48
00:19:52.965     should retrieve the change
00:19:52.965     /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/diff_test.go:47
00:19:52.965 
00:19:52.965     Expected
00:19:52.965         <int>: 126
00:19:52.965     to equal
00:19:52.965         <int>: 0
00:19:52.966 
00:19:52.966     /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/diff_test.go:34
```
The reason is that this PR on the agent solves some issues about STDIN not being closed. Indeed, by properly closing STDIN when it is closed on the host (detected by the shim), the container process returns. In this case we can see the root cause:
```
Stdout: oci runtime error: Container not running, impossible to enter
```
The solution for this test is to run the container as detached but with `-i` flag so that it can expect some input to come, and it won't terminate.

### PR DESCRIPTION
**Pull request by sboeuf**
integration: docker: Fix diff test by making sure the container runs
    
    The diff test needs to use -i flag in order to keep the container
    process running while a "docker exec" is started. This issue was
    not visible before because STDIN was never closed on the agent side,
    even if it was on the host side. With recent patch from the agent,
    this issue got highlighted.
    
    Fixes #705
    
    Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@grahamwhaley if you're fine with this change, please merge it, and as a follow up, could you re-trigger failing builds (fedora26 and ubuntu16.04) from this PR: https://github.com/clearcontainers/agent/pull/162

File: integration/docker/diff_test.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ var _ = Describe("diff", func() {
 
 	BeforeEach(func() {
 		id = randomDockerName()
-		_, _, exitCode := DockerRun("--name", id, "-d", Image, "sh")
+		_, _, exitCode := DockerRun("--name", id, "-di", Image, "sh")
```
Comment (grahamwhaley) [inline integration/docker/diff_test.go]: The fix looks like it should work - but, is it the right fix?
Given we don't actually use the `sh` afaict, I suspect we'd be more 'correct' launching a benign permanent process here - my normal choice is `tail -f /dev/null` for instance.
I don't know if there is a docker idiom for doing this - for having a pre-made container sat waiting to run `exec`s - anybody? This feels awfully like our 'pause' container :-)

Comment (jodh-intel) [reply integration/docker/diff_test.go]: I agree that `tail -f /dev/null` would signal the intent of the test more clearly, so would indeed be better.

But this change is the minimal fix for the test. How about a compromise where @sboeuf adds a comment explaining why the `-i` is being used?

Comment (sboeuf) [reply integration/docker/diff_test.go]: I am okay modifying the command instead of the flag here. The goal is to maintain the container running, I don't care the way we do this.

**Comment by sboeuf** [comment]
@grahamwhaley @jodh-intel comment addressed, let me know if this looks okay now !

**Comment by jodh-intel** [comment]
I think you could drop the `sh -c` as well, but

lgtm.

**Comment by grahamwhaley** [comment]
CI looked like it worked, and then looked like it failed - I think I caught it half way through the PR being updated. Anyhow, now it looks like the modified test is failing? From the 16.04 logs:
```
16:18:13  • [SLOW TEST:5.544 seconds]
16:18:13  docker search
16:18:13  /home/jenkins/jenkins_slave/workspace/clear-containers-tests-fedora-26-PR/go/src/github.com/clearcontainers/tests/integration/docker/search_test.go:36
16:18:13    search an image
16:18:13    /home/jenkins/jenkins_slave/workspace/clear-containers-tests-fedora-26-PR/go/src/github.com/clearcontainers/tests/integration/docker/search_test.go:35
16:18:13      should filter the requests
16:18:13      /home/jenkins/jenkins_slave/workspace/clear-containers-tests-fedora-26-PR/go/src/github.com/clearcontainers/tests/integration/docker/search_test.go:34
16:18:13  ------------------------------
16:18:13  
16:18:13  
16:18:13  Summarizing 1 Failure:
16:18:13  
16:18:13  [Fail] diff [BeforeEach] inspect changes in a container should retrieve the change 
16:18:15  /home/jenkins/jenkins_slave/workspace/clear-containers-tests-fedora-26-PR/go/src/github.com/clearcontainers/tests/integration/docker/diff_test.go:32
```
