### PR TITLE
localCI: fix golang static checks

### LINKED ISSUE #233: static checks: localCI code fails golang static checks
The localCI code tree is currently failing the golang static checks we are trying to land in #110 
Please fix up all reported issues so we can land #110 

Current report looks like:
```
19 main (*Repo).runTest /work/gwhaley/gopath/src/github.com/clearcontainers/tests/cmd/localCI/repo.go:374:1
16 main (*Repo).setup /work/gwhaley/gopath/src/github.com/clearcontainers/tests/cmd/localCI/repo.go:112:1
```

### PR DESCRIPTION
**Pull request by devimc**
this patch strip setup and runTests functions in several functions
in order to reduce the cyclomatic complexities of them and
be in compliance with gocyclo

fixes #233

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: cmd/localCI/repo.go [hunk 1]
```diff
@@ -127,22 +119,48 @@ func (r *Repo) setup() error {
...
 	// get the control version repository
 	r.cvr, err = newCvr(r.URL, r.Token)
-	if err != nil {
-		return err
+
+	return err
+}
+
+func (r *Repo) setupLogServer() error {
+	if reflect.DeepEqual(r.LogServer, LogServer{}) {
```
Comment (jodh-intel) [inline cmd/localCI/repo.go]: Neat! ;)

**Comment by grahamwhaley** [comment]
lgtm
