### PR TITLE
test: Fix issue of static checks inspect test

### LINKED ISSUE #232: static checks: integration tests failing golang static checks
The integration subdir is failing with the script we are trying to land in #110 
Please fix up the reported issues so we can land #110 and prevent any further items creeping in.

Errors reported at present up until the script quite look like:

```
ERROR: 'gofmt -s -d -l' found problems:
./integration/docker/inspect_test.go
diff ./integration/docker/inspect_test.go gofmt/./integration/docker/inspect_test.go
--- /tmp/gofmt342357166	2017-07-21 12:55:44.062227548 +0100
+++ /tmp/gofmt893873717	2017-07-21 12:55:44.062227548 +0100
@@ -23,11 +23,11 @@
 	. "github.com/onsi/gomega"
 )
 
-func inspectFormatOptions (formatOption string) TableEntry {
+func inspectFormatOptions(formatOption string) TableEntry {
 	return Entry(fmt.Sprintf("inspect with %s", formatOption), formatOption)
 }
 
-var _= Describe ("inspect", func() {
+var _ = Describe("inspect", func() {
 	var (
 		args []string
 		id   string
@@ -57,7 +57,7 @@
 			exitCode := command.Run()
 			Expect(exitCode).To(Equal(0))
 			Expect(command.Stdout.String()).To(ContainSubstring(Image))
- 			Expect(command.Stdout.String()).NotTo(BeEmpty())
+			Expect(command.Stdout.String()).NotTo(BeEmpty())
 		},
 		inspectFormatOptions("'{{.Config.Image}}'"),
 		inspectFormatOptions("'{{json .Config}}'"),
```

### PR DESCRIPTION
**Pull request by GabyCT**
Check issues reported by static checks

Fixes #232

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

File: integration/docker/inspect_test.go [hunk 1]
```diff
@@ -23,11 +23,11 @@ import (
 	. "github.com/onsi/gomega"
 )
 
-func inspectFormatOptions (formatOption string) TableEntry {
+func inspectFormatOptions(formatOption string) TableEntry {
 	return Entry(fmt.Sprintf("inspect with %s", formatOption), formatOption)
 }
 
-var _= Describe ("inspect", func() {
+var _ = Describe ("inspect", func() {
```
Comment (grahamwhaley) [inline integration/docker/inspect_test.go]: Hi. I think you only fixed one ' ' anomaly. There was another reported with the `Describe (` as well ;-) (two space errors on the same line that is). `go-static-checks` is still complaining for me. Did you check your fixes by running it?

**Comment by devimc** [comment]
lgtm
