### PR TITLE
integration: change docker rmi timeout

### LINKED ISSUE #404: integration: docker build test fails randomly in semaphoreCI
```
Running command '/usr/bin/docker [docker build -t test /home/runner/workspace/src/github.com/clearcontainers/tests/Dockerfiles/BuildTest]'
[docker build -t test /home/runner/workspace/src/github.com/clearcontainers/tests/Dockerfiles/BuildTest]
Timeout: 5 seconds
Exit Code: 0
Stdout: Sending build context to Docker daemon   2.56kB


Step 1/4 : FROM busybox
 ---> efe10ee6727f
Step 2/4 : ENV VAR "test_env_vars"
 ---> Running in 14285d2bad1d
 ---> c5dcd9d8dffe
Removing intermediate container 14285d2bad1d
Step 3/4 : RUN sh -c 'env'
 ---> Running in 2e9710b0472b
HOSTNAME=44c72a15738e
SHLVL=2
HOME=/root
VAR=test_env_vars
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
 ---> 131cf3987e39
Removing intermediate container 2e9710b0472b
Step 4/4 : CMD /bin/bash
 ---> Running in 8acd17b4b228
 ---> 24fcaf50d1dd
Removing intermediate container 8acd17b4b228
Successfully built 24fcaf50d1dd
Successfully tagged test:latest

Stderr: 
Running command '/usr/bin/docker [docker run --rm -t --name wQ5zY8a1ajL1a7aP336nfhlpAcotfO test sh -c 'env']'
[docker run --rm -t --name wQ5zY8a1ajL1a7aP336nfhlpAcotfO test sh -c 'env']
Timeout: 5 seconds
Exit Code: 0
Stdout: HOSTNAME=6257a108a226

SHLVL=1

HOME=/root

VAR=test_env_vars

TERM=xterm

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

PWD=/


Stderr: 
Running command '/usr/bin/docker [docker rmi test]'
Killing process timeout reached '5' seconds
• Failure in Spec Teardown (AfterEach) [10.977 seconds]
build
/home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/build_test.go:61
  build with docker [AfterEach]
  /home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/build_test.go:60
    docker build env vars
    /home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/build_test.go:59
      should display env vars
      /home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/build_test.go:58

      Expected
          <int>: -1
      to equal
          <int>: 0

      /home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/build_test.go:42
------------------------------
•

Summarizing 5 Failures:

[Fail] run container with docker [It] with 'true' as workload 
/home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/run_test.go:54

[Fail] load [AfterEach] load with docker load a container should load image 
/home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/main_test.go:33

[Fail] docker commit commit a container with new configurations [It] should have the new configurations 
/home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/commit_test.go:52

[Fail] docker create check create functionality [It] create a container 
/home/runner/workspace/src/github.com/clearcontainers/tests/integration/docker/create_test.go:42

[Fail] build [AfterEach] build with docker docker build env vars should display env vars 
```

### PR DESCRIPTION
**Pull request by devimc**
docker rmi does not involve to the runtime hence
the time used to complete this task does not matter

fixes #404

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: docker.go [hunk 1]
```diff
@@ -170,7 +170,10 @@ func DockerImages(args ...string) (string, string, int) {
 
 // DockerRmi removes one or more images
 func DockerRmi(args ...string) (string, string, int) {
-	return runDockerCommand("rmi", args...)
+	// docker takes more than 5 seconds to remove an image, it depends
+	// of the image size and this operation does not involve to the
+	// runtime, 15 seconds should be enough to complete this task
+	return runDockerCommandWithTimeout(15, "rmi", args...)
```
Comment (jodh-intel) [inline docker.go]: I'd rather this was defined at the top of the file as a variable to make it stand out (maybe even also allow the value to be overridden using an env var?)

Comment (devimc) [inline docker.go]: sure , I can add it at the top of the file
