### PR TITLE
 localCI: do not re-test a pull request failed

### LINKED ISSUE #416: localCI: do not re-test a pull request failed
localCI re-tests a pull request failed even if it has not changed (no new commits), this is a wrong behavior because a pull request must be re-tested only when it has changed (new commits)

### PR DESCRIPTION
**Pull request by devimc**
localCI re-tests a pull request failed even if it has not
changed (no new commits), this is a wrong behavior because a
pull request must be re-tested only when it has
changed (new commits).

fixes #416

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: cmd/localCI/repo.go [hunk 1]
```diff
@@ -363,69 +388,57 @@ func (r *Repo) test() error {
...
+	// test revision
+	return r.testRevision(rev, langEnv)
 }
 
-// runTest generate an environment and run the stages
-func (r *Repo) runTest(rev revision) error {
+// setupRevision generates a language environment, downloads the revision
+// and creates the logs directory
+func (r *Repo) setupRevision(rev revision) (languageConfig, error) {
+	// generate a new environment to runt the stages
```
Comment (chavafg) [inline cmd/localCI/repo.go]: typo: s/runt/run

**Comment by chavafg** [comment]
lgtm
