### PR TITLE
tests: Fix docker load test to use docker.go functions

### LINKED ISSUE #428: Fix docker load test to use docker.go functions
Fix docker load test to use docker.go functions like Rmi and commit

### PR DESCRIPTION
**Pull request by GabyCT**
Fix docker load test to use docker.go functions like rmi and commit

Fixes #428

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

File: integration/docker/load_test.go [hunk 1]
```diff
@@ -53,8 +53,9 @@ var _ = Describe("load", func() {
 				defer os.Remove(file.Name())
 				Expect(file.Name()).To(BeAnExistingFile())
 				imageName = "test/container-test"
-				args = []string{"commit", id, imageName}
-				runDockerCommand(0, args...)
+				args = []string{id, imageName}
+				_, _, exitCode := DockerCommit(args...)
```
Comment (devimc) [inline integration/docker/load_test.go]: args is not needed
```
_, _, exitCode := DockerCommit(id, imageName)
```

**Comment by GabyCT** [comment]
@devimc changes applied
