### PR TITLE
functional: refactor some functional tests

### LINKED ISSUE #65: ginkgo shows error messages of some functional tests
Running functional tests ```ginkgo``` shows error messages of some functional tests. This is an unexpected behavior since error messages must be only shown when a test fails

````
Running command '/home/juliomon/gopath/src/github.com/clearcontainers/runtime/cc-runtime [cc-runtime create]'
command failed error 'exit status 1'
Running command '/home/juliomon/gopath/src/github.com/clearcontainers/runtime/cc-runtime [cc-runtime delete]'
command failed error 'exit status 1'
Running command '/home/juliomon/gopath/src/github.com/clearcontainers/runtime/cc-runtime [cc-runtime delete hRJGyVB2BZ7VZwcbqMO9g1NGbEYxTb]'
command failed error 'exit status 1'
................................
```

### PR DESCRIPTION
**Pull request by devimc**
this patch refactors some functional test since they are bad designed
and ginkgo shows theirs error messages

fixes #65

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: functional/commands_test.go [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+}
+
+var _ = Describe("commands", func() {
+	var exitCode int
+
+	DescribeTable("without a container ID should fail",
+		func(cmd *Command) {
+			exitCode = cmd.Run()
+
+			Ω(exitCode).ShouldNot(Equal(0))
```
Comment (jodh-intel) [inline functional/commands_test.go]: Soooo many jokes:

- I'm all for i18n, but... wow! :smile:
- This is just all Greek to me.
- Omegod!

I could go on, but,

lgtm.

**Comment by jodh-intel** [comment]
lgtm (again)

**Comment by chavafg** [comment]
lgtm
